language: node_js
node_js:
 - "10.16.3"
cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_script:
  - psql -c 'create database mydiary;' -U postgres

script:
  - "npm run test"
after_success: npm run coverage

