install:
 - npm install
 services:
 - postgresql
 before_script:
 - psql -c 'CREATE DATABASE mydiary;' -U postgres
 notifications:
 email: false
 script:
 - "npm run test"
 sudo: false
language: node_js
node_js:
  - "10"
cache:
directories:
  - "node_modules"
before_sucess:
  - npm test
after_success:
  - npm run coverage
